In [1]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## sample_submission_zero.csv(Testing Set)
### the test set, containing the user ids, in the format that we expect you to submit
#### is_churn: <font color=#0000FF> This is what you will predict. Churn is defined as whether the user did not continue the subscription within 30 days of expiration. is_churn = 1 means 流失,is_churn = 0 means renewal.

In [2]:
kk_submission = pd.read_csv("sample_submission_zero.csv")

In [3]:
kk_submission.head()

msno  is_churn
0  ugx0CjOMzazClkFzU2xasmDZaoIqOUAZPsH1q0teWCg=         0
1  f/NmvEzHfhINFEYZTR05prUdr+E+3+oewvweYz9cCQE=         0
2  zLo9f73nGGT1p21ltZC3ChiRnAVvgibMyazbCxvWPcg=         0
3  8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=         0
4  K6fja4+jmoZ5xG6BypqX80Uw/XKpMgrEMdG2edFOxnA=         0

In [4]:
kk_submission["is_churn"].unique()

array([0], dtype=int64)

In [5]:
print((kk_submission["is_churn"] == 0).sum())
print((kk_submission["is_churn"] == 1).sum())

970960
0


## sample_submission_v2.csv
### same format as sample_submission_zero.csv, refreshed 11/06/2017, contains the test data for April, 2017.

In [7]:
kk_submissionV2 = pd.read_csv("sample_submission_v2.csv")

In [8]:
kk_submissionV2.head()

msno  is_churn
0  4n+fXlyJvfQnTeKXTWT507Ll4JVYGrOC8LHCfwBmPE4=         0
1  aNmbC1GvFUxQyQUidCVmfbQ0YeCuwkPzEdQ0RwWyeZM=         0
2  rFC9eSG/tMuzpre6cwcMLZHEYM89xY02qcz7HL4//jc=         0
3  WZ59dLyrQcE7ft06MZ5dj40BnlYQY7PHgg/54+HaCSE=         0
4  aky/Iv8hMp1/V/yQHLtaVuEmmAxkB5GuasQZePJ7NU4=         0

In [9]:
kk_submissionV2["is_churn"].unique()

array([0], dtype=int64)

In [10]:
print((kk_submissionV2["is_churn"] == 0).sum())
print((kk_submissionV2["is_churn"] == 1).sum())

907471
0


## 小結: <font color=#FF3333> sample_submission與sample_submissionV2沒有流失值(?

## 合併submission

In [11]:
kk_Test = pd.concat([kk_submission, kk_submissionV2], axis=0)

In [12]:
kk_Test.head()

msno  is_churn
0  ugx0CjOMzazClkFzU2xasmDZaoIqOUAZPsH1q0teWCg=         0
1  f/NmvEzHfhINFEYZTR05prUdr+E+3+oewvweYz9cCQE=         0
2  zLo9f73nGGT1p21ltZC3ChiRnAVvgibMyazbCxvWPcg=         0
3  8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=         0
4  K6fja4+jmoZ5xG6BypqX80Uw/XKpMgrEMdG2edFOxnA=         0

## ======================================================================

## train.csv
### the train set, containing the user ids and whether they have churned.
#### A. msno: <font color=#0000FF> user id
#### B. is_churn: <font color=#0000FF> This is the target variable. Churn is defined as whether the user did not continue the subscription within 30 days of expiration. is_churn = 1 means churn,is_churn = 0 means renewal.

In [13]:
kk_train = pd.read_csv("train.csv")

In [14]:
kk_train.head()

msno  is_churn
0  waLDQMmcOu2jLDaV1ddDkgCrB/jl6sD66Xzs0Vqax1Y=         1
1  QA7uiXy8vIbUSPOkCf9RwQ3FsT8jVq2OxDr8zqa7bRQ=         1
2  fGwBva6hikQmTJzrbz/2Ezjm5Cth5jZUNvXigKK2AFA=         1
3  mT5V8rEpa+8wuqi6x0DoVd3H5icMKkE9Prt49UlmK+4=         1
4  XaPhtGLk/5UvvOYHcONTwsnH97P4eGECeq+BARGItRw=         1

In [15]:
kk_train["is_churn"].unique()

array([1, 0], dtype=int64)

In [17]:
print((kk_train["is_churn"] == 0).sum())
print((kk_train["is_churn"] == 1).sum())

929460
63471


## train_v2.csv
### same format as train.csv, refreshed 11/06/2017, contains the churn data for March, 2017.

In [18]:
kk_trainV2 = pd.read_csv("train_v2.csv")

In [19]:
kk_trainV2.head()

msno  is_churn
0  ugx0CjOMzazClkFzU2xasmDZaoIqOUAZPsH1q0teWCg=         1
1  f/NmvEzHfhINFEYZTR05prUdr+E+3+oewvweYz9cCQE=         1
2  zLo9f73nGGT1p21ltZC3ChiRnAVvgibMyazbCxvWPcg=         1
3  8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=         1
4  K6fja4+jmoZ5xG6BypqX80Uw/XKpMgrEMdG2edFOxnA=         1

In [20]:
kk_trainV2["is_churn"].unique()

array([1, 0], dtype=int64)

In [21]:
print((kk_trainV2["is_churn"] == 0).sum())
print((kk_trainV2["is_churn"] == 1).sum())

883630
87330


## ----------------------------------------------------------------------------------------------------------------------------

## Training Data(合併train與train_v2)

In [22]:
kk_training = pd.concat([kk_train, kk_trainV2], axis=0)

In [23]:
kk_training.shape

(1963891, 2)

In [24]:
kk_training.head()

msno  is_churn
0  waLDQMmcOu2jLDaV1ddDkgCrB/jl6sD66Xzs0Vqax1Y=         1
1  QA7uiXy8vIbUSPOkCf9RwQ3FsT8jVq2OxDr8zqa7bRQ=         1
2  fGwBva6hikQmTJzrbz/2Ezjm5Cth5jZUNvXigKK2AFA=         1
3  mT5V8rEpa+8wuqi6x0DoVd3H5icMKkE9Prt49UlmK+4=         1
4  XaPhtGLk/5UvvOYHcONTwsnH97P4eGECeq+BARGItRw=         1

In [46]:
print((kk_training["is_churn"] == 0).sum())
print((kk_training["is_churn"] == 1).sum())

1813090
150801


## 小結: <font color=#FF3333> 流失人數 vs 續約人數比例差異較大(超過9:1)

## ====================================================================

## members.csv
### user information. Note that not every user in the dataset is available.
#### A. bd: age. Note: <font color=#0000FF> this column has outlier values ranging from -7000 to 2015, please use your judgement.
#### B. registered_via:<font color=#0000FF>  registration method
#### C. registration_init_time: <font color=#0000FF> format %Y%m%d
#### D. expiration_date: <font color=#0000FF> format %Y%m%d, taken as a snapshot at which the member.csv is extracted. Not representing the actual churn behavior.

In [25]:
kk_members = pd.read_csv("members_v3.csv")

In [26]:
kk_members.head()

msno  city  bd  gender  \
0  Rb9UwLQTrxzBVwCB6+bCcSQWZ9JiNLC9dXtM1oEsZA8=     1   0     NaN   
1  +tJonkh+O1CA796Fm5X60UMOtB6POHAwPjbTRVl/EuU=     1   0     NaN   
2  cV358ssn7a0f7jZOwGNWS07wCKVqxyiImJUX6xcIwKw=     1   0     NaN   
3  9bzDeJP6sQodK73K5CBlJ6fgIQzPeLnRl0p5B77XP+g=     1   0     NaN   
4  WFLY3s7z4EZsieHCt63XrsdtfTEmJ+2PnnKLH5GY4Tk=     6  32  female   

   registered_via  registration_init_time  
0              11                20110911  
1               7                20110914  
2              11                20110915  
3              11                20110915  
4               9                20110915

In [27]:
print(kk_members.shape)  # 共6769473筆資料
print(kk_members["gender"].unique())
print(kk_members["gender"].isnull().sum())  # 性別項空值有442萬項
print((kk_members["gender"] == "female").sum())  # 女性人數1144613
print((kk_members["gender"] == "male").sum())  # 男性人數1195355

(6769473, 6)
[nan 'female' 'male']
4429505
1144613
1195355


## =======================================================================

## transactions.csv
### transactions of users up until 2/28/2017.
#### A. msno: <font color=#0000FF> user id
#### B. payment_method_id:<font color=#0000FF>  payment method
#### C. payment_plan_days: <font color=#0000FF> length of membership plan in days
#### D. plan_list_price: <font color=#0000FF> in New Taiwan Dollar (NTD)
#### E. actual_amount_paid: <font color=#0000FF> in New Taiwan Dollar (NTD)
#### F. transaction_date: <font color=#0000FF> format %Y%m%d
#### G. membership_expire_date: <font color=#0000FF> format %Y%m%d
#### H. is_cancel: <font color=#0000FF> whether or not the user canceled the membership in this transaction.

In [28]:
kk_transac = pd.read_csv("transactions.csv")

In [29]:
kk_transac.head()

msno  payment_method_id  \
0  YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc=                 41   
1  AZtu6Wl0gPojrEQYB8Q3vBSmE2wnZ3hi1FbK1rQQ0A4=                 41   
2  UkDFI97Qb6+s2LWcijVVv4rMAsORbVDT2wNXF0aVbns=                 41   
3  M1C56ijxozNaGD0t2h68PnH2xtx5iO5iR2MVYQB6nBI=                 39   
4  yvj6zyBUaqdbUQSrKsrZ+xNDVM62knauSZJzakS9OW4=                 39   

   payment_plan_days  plan_list_price  actual_amount_paid  is_auto_renew  \
0                 30              129                 129              1   
1                 30              149                 149              1   
2                 30              129                 129              1   
3                 30              149                 149              1   
4                 30              149                 149              1   

   transaction_date  membership_expire_date  is_cancel  
0          20150930                20151101          0  
1          20150930                20151031          0  
2          20150930                20160427          0  
3          20150930                20151128          0  
4          20150930                20151121          0

## transactions_v2.csv

### same format as transactions.csv, refreshed 11/06/2017, contains the transactions data until 3/31/2017.

In [30]:
kk_transacV2 = pd.read_csv("transactions_v2.csv")

In [31]:
kk_transacV2.head()

msno  payment_method_id  \
0  ++6eU4LsQ3UQ20ILS7d99XK8WbiVgbyYL4FUgzZR134=                 32   
1  ++lvGPJOinuin/8esghpnqdljm6NXS8m8Zwchc7gOeA=                 41   
2  +/GXNtXWQVfKrEDqYAzcSw2xSPYMKWNj22m+5XkVQZc=                 36   
3  +/w1UrZwyka4C9oNH3+Q8fUf3fD8R3EwWrx57ODIsqk=                 36   
4  +00PGzKTYqtnb65mPKPyeHXcZEwqiEzktpQksaaSC3c=                 41   

   payment_plan_days  plan_list_price  actual_amount_paid  is_auto_renew  \
0                 90              298                 298              0   
1                 30              149                 149              1   
2                 30              180                 180              1   
3                 30              180                 180              1   
4                 30               99                  99              1   

   transaction_date  membership_expire_date  is_cancel  
0          20170131                20170504          0  
1          20150809                20190412          0  
2          20170303                20170422          0  
3          20170329                20170331          1  
4          20170323                20170423          0

## ----------------------------------------------------------------------------------------------------------------------------

## 合併Transaction與Transaction2(交易項目)

In [32]:
kk_transaction = pd.concat([kk_transac, kk_transacV2], axis=0)

In [33]:
kk_transaction.head()

msno  payment_method_id  \
0  YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc=                 41   
1  AZtu6Wl0gPojrEQYB8Q3vBSmE2wnZ3hi1FbK1rQQ0A4=                 41   
2  UkDFI97Qb6+s2LWcijVVv4rMAsORbVDT2wNXF0aVbns=                 41   
3  M1C56ijxozNaGD0t2h68PnH2xtx5iO5iR2MVYQB6nBI=                 39   
4  yvj6zyBUaqdbUQSrKsrZ+xNDVM62knauSZJzakS9OW4=                 39   

   payment_plan_days  plan_list_price  actual_amount_paid  is_auto_renew  \
0                 30              129                 129              1   
1                 30              149                 149              1   
2                 30              129                 129              1   
3                 30              149                 149              1   
4                 30              149                 149              1   

   transaction_date  membership_expire_date  is_cancel  
0          20150930                20151101          0  
1          20150930                20151031          0  
2          20150930                20160427          0  
3          20150930                20151128          0  
4          20150930                20151121          0

In [34]:
kk_transaction.shape # 共22978755筆資料，9個特徵

(22978755, 9)

In [35]:
(kk_transaction["msno"] == "YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc=").sum() # 取某個user的交易資料筆數有27筆

27

In [36]:
kk_transaction[kk_transaction["msno"] == "YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc="].head(10) # 取此user某10筆交易資料

msno  payment_method_id  \
0         YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc=                 41   
753139    YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc=                 41   
1234428   YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc=                 41   
1917887   YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc=                 41   
1957479   YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc=                 41   
3482816   YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc=                 41   
5413134   YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc=                 41   
7106202   YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc=                 41   
7619099   YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc=                 41   
10161584  YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc=                 41   

          payment_plan_days  plan_list_price  actual_amount_paid  \
0                        30              129                 129   
753139                   30              129                 129   
1234428                  30              129                 129   
1917887                  30              129                 129   
1957479                  30              129                 129   
3482816                  30              129                 129   
5413134                  30              129                 129   
7106202                  30              129                 129   
7619099                  30              129                 129   
10161584                 30              129                 129   

          is_auto_renew  transaction_date  membership_expire_date  is_cancel  
0                     1          20150930                20151101          0  
753139                1          20151031                20151201          0  
1234428               1          20150630                20150801          0  
1917887               1          20150228                20150401          0  
1957479               1          20161130                20170101          0  
3482816               1          20150731                20150901          0  
5413134               1          20160430                20160601          0  
7106202               1          20160731                20160901          0  
7619099               1          20150131                20150301          0  
10161584              1          20160831                20161001          0

## 小結: <font color=#FF3333> Transaction的msno有重複的，表示同一個人有很多次交易紀錄

## =======================================================================

## user_logs.csv
### daily user logs describing listening behaviors of a user. Data collected until 2/28/2017.
#### A. date: <font color=#0000FF> format %Y%m%d
#### B. num_25: <font color=#0000FF> # of songs played less than 25% of the song length
#### C. num_985: <font color=#0000FF> # of songs played between 75% to 98.5% of the song length
#### D. total_secs: <font color=#0000FF> total seconds played

In [ ]:
# 檔案太大，先不取
"""
kk_userlog = pd.read_csv("user_logs.csv", sep=',',engine = 'python',iterator=True)
loop = True
chunkSize = 1000
chunks = []
index=0
while loop:
    try:
        print(index)
        chunk = kk_userlog.get_chunk(chunkSize)
        chunks.append(chunk)
        index+=1

    except StopIteration:
        loop = False
        print("Iteration is stopped.")
print('Start')
kk_userlog = pd.concat(chunks, ignore_index= True)
"""

In [39]:
# kk_userlog

## user_logs_v2.csv
### same format as user_logs.csv, refreshed 11/06/2017, contains the user logs data until 3/31/2017.

In [37]:
kk_userlogV2 = pd.read_csv("user_logs_v2.csv")

In [38]:
kk_userlogV2.head()

msno      date  num_25  num_50  \
0  u9E91QDTvHLq6NXjEaWv8u4QIqhrHk72kE+w31Gnhdg=  20170331       8       4   
1  nTeWW/eOZA/UHKdD5L7DEqKKFTjaAj3ALLPoAWsU8n0=  20170330       2       2   
2  2UqkWXwZbIjs03dHLU9KHJNNEvEkZVzm69f3jCS+uLI=  20170331      52       3   
3  ycwLc+m2O0a85jSLALtr941AaZt9ai8Qwlg9n0Nql5U=  20170331     176       4   
4  EGcbTofOSOkMmQyN1NMLxHEXJ1yV3t/JdhGwQ9wXjnI=  20170331       2       1   

   num_75  num_985  num_100  num_unq  total_secs  
0       0        1       21       18    6309.273  
1       1        0        9       11    2390.699  
2       5        3       84      110   23203.337  
3       2        2       19      191    7100.454  
4       0        1      112       93   28401.558

## ========================================================================

In [39]:
print(f'submission: {kk_submission.shape}')
print(f'submissionV2: {kk_submissionV2.shape}')
print(f'members: {kk_members.shape}')
print(f'train: {kk_train.shape}')
print(f'trainV2: {kk_trainV2.shape}')
print(f'TrainingData: {kk_training.shape}')
print(f'transac: {kk_transac.shape}')
print(f'transacV2: {kk_transacV2.shape}')
print(f'userlogV2: {kk_userlogV2.shape}')

submission: (970960, 2)
submissionV2: (907471, 2)
members: (6769473, 6)
train: (992931, 2)
trainV2: (970960, 2)
TrainingData: (1963891, 2)
transac: (21547746, 9)
transacV2: (1431009, 9)
userlogV2: (18396362, 9)


## 合併Training與Members欄位(取相同msno)

In [40]:
kk_Training_Members = pd.merge(kk_training, kk_members, how="left", on="msno")

In [41]:
kk_Training_Members.head()

msno  is_churn  city    bd  gender  \
0  waLDQMmcOu2jLDaV1ddDkgCrB/jl6sD66Xzs0Vqax1Y=         1  18.0  36.0  female   
1  QA7uiXy8vIbUSPOkCf9RwQ3FsT8jVq2OxDr8zqa7bRQ=         1  10.0  38.0    male   
2  fGwBva6hikQmTJzrbz/2Ezjm5Cth5jZUNvXigKK2AFA=         1  11.0  27.0  female   
3  mT5V8rEpa+8wuqi6x0DoVd3H5icMKkE9Prt49UlmK+4=         1  13.0  23.0  female   
4  XaPhtGLk/5UvvOYHcONTwsnH97P4eGECeq+BARGItRw=         1   3.0  27.0    male   

   registered_via  registration_init_time  
0             9.0              20050406.0  
1             9.0              20050407.0  
2             9.0              20051016.0  
3             9.0              20051102.0  
4             9.0              20051228.0

In [42]:
kk_Training_Members.shape  # 有196萬筆資料

(1963891, 7)

In [43]:
print(kk_Training_Members.isnull().sum()/len(kk_Training_Members))

msno                      0.000000
is_churn                  0.000000
city                      0.114957
bd                        0.114957
gender                    0.602525
registered_via            0.114957
registration_init_time    0.114957
dtype: float64
